baseURL = 'https://mattgoodrich.com/'
timeout = '120s'
languageCode = 'en-us'
title = 'Matt Goodrich'
theme = "hugo-theme-stack"
ignoreFiles = ['\.mmd$']

[taxonomies]
  category = 'categories'
  tag = 'tags'
  genre = 'genres'

[params]
  mainSections = ['posts']
  featuredImageField = 'image'
  rssFullContent = true
  favicon = "favicon.png"

  [params.sidebar]
    subtitle = "Private pilot. Security leader. Husband. Father."
    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/avatar.jpg"

  [params.article]
    toc = true
    readingTime = true

  [params.colorScheme]
    toggle = true
    default = "auto"

  [[params.widgets.homepage]]
    type = "search"
  [[params.widgets.homepage]]
    type = "archives"
  [[params.widgets.homepage]]
    type = "tag-cloud"
  [[params.widgets.page]]
    type = "toc"

[menu]
  [[menu.social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/matthewg00drich/"
    [menu.social.params]
      icon = "brand-linkedin"

  [[menu.social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/mgoodric"
    [menu.social.params]
      icon = "brand-github"

[services.googleAnalytics]
  ID = 'G-RHWWVR0716'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
